---
# tasks file for docker_debian
- name: Uninstall old versions of Docker
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add Docker repository key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

  register: add_repository_key
  ignore_errors: true

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
    state: present

- name: Install packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
